### PR TITLE
Formatting immediately

### PR DESCRIPTION
**Pull request by romkatsu**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/data-response/issues/35

### CODE REVIEW

**Comment by samdark** [comment]
Should be checked with application templates.

**Comment by romkatsu** [comment]
it doesn't work as there is a loop here https://github.com/yiisoft/app-api/blob/master/src/Formatter/ApiResponseFormatter.php#L28

**Comment by romkatsu** [comment]
it turns out that we can't format in getters and setters since this will come to the loop if the method is called in the formatter

I suggest making one method that will return a formatted response - getFormattedResponse()

what do you think?

**Comment by samdark** [comment]
> it turns out that we can't format in getters and setters since this will come to the loop if the method is called in the formatter

Is it true if we'll do it this way?

```php
private $fomatted = null;

public function getFormatted()
{
    if ($this->formatted !== null) {
        return $this->formatted;
    }

    return $this->formatted = format($this->data);
}
```

**Comment by yiiliveext** [comment]
> > it turns out that we can't format in getters and setters since this will come to the loop if the method is called in the formatter
> 
> Is it true if we'll do it this way?
> 
> ```
> private $fomatted = null;
> 
> public function getFormatted()
> {
>     if ($this->formatted !== null) {
>         return $this->formatted;
>     }
> 
>     return $this->formatted = format($this->data);
> }
> ```

This isn't compatible with ResponseInterface

**Comment by samdark** [comment]
I've meant using response methods, of course. That was just an example.

**Comment by romkatsu** [comment]
> > it turns out that we can't format in getters and setters since this will come to the loop if the method is called in the formatter
> 
> Is it true if we'll do it this way?
> 
> ```
> private $fomatted = null;
> 
> public function getFormatted()
> {
>     if ($this->formatted !== null) {
>         return $this->formatted;
>     }
> 
>     return $this->formatted = format($this->data);
> }
> ```

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Good!

**Pull request merged**
